palette = "catppuccin_latte"
format = """
[â–‘â–’â–“](mauve)\
$directory\
$git_branch$git_status$git_state\
$rust\
$python\
[â–“â–’â–‘](fg:lavender)\
$jobs\
\n$character"""
add_newline = false
continuation_prompt = "[â–¸â–¹ ](bold mauve)"

[character]
success_symbol = "[ó±˜Š ](bold mauve)"
error_symbol = "[ó±˜Š ](bold red)"
vimcmd_symbol = "[î˜« ](bold mauve)"

[os]
disabled = false
style = "bg:mauve fg:base"

[jobs]
symbol = " ó°’² "

[os.symbols]
Manjaro = " ó±˜Š "

[directory]
style = "fg:base bg:pink"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "ó°‡˜/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "î¾ "
style = "bg:lavender"
format = '[[ $symbol $branch ](fg:base bg:lavender)]($style)'

[git_status]
style = "bg:lavender"
format = '[[($all_status$ahead_behind )](fg:base bg:lavender)]($style)'

[rust]
symbol = "ğŸ¦€"
style = "bg:teal fg:base"
format = '[[ $symbol ($version) ]($style)]($style)'

[python]
symbol = "ğŸ"
style = "bg:teal fg:base"
format = '[[ $symbol ($version) ]($style)]($style)'

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
